#!/bin/bash

MINPARAMS=3
FILENAME=$1
SUFFIX=$2
MDINFILES=$[$3+1]

module load gcc/4.7.0 
module load mvapich2/gnu/ib/2.2
module load amber/18-mvapich2
e=0
f=1
while [ $f -lt $MDINFILES ]; do

mpirun -np 20 -hostfile $PWD/PBS_NODEFILE $AMBERHOME/bin/pmemd.MPI -O -i mdin.$f \
-o ${FILENAME}_${SUFFIX}$f.out \
-p ${FILENAME}.prmtop \
-c ${FILENAME}_${SUFFIX}$e.rst \
-r ${FILENAME}_${SUFFIX}$f.rst \
-x ${FILENAME}_${SUFFIX}$f.mdcrd \
-ref ${FILENAME}_${SUFFIX}$e.rst

e=$[$e+1]
f=$[$f+1]
done
