#!/usr/bin/env python3
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import argparse

def attribute_to_residues(array,filename,attribute,description):
    ### Takes an array of values (per residue) and created a chimera-compatible attribute file.
    ### This file is used by chimera to assign color values to each residue.
    f = open(filename,"w+")
    f.write("#"+str(description)+"\n")
    f.write("attribute: "+str(attribute)+"\n")
    f.write("match mode: 1-to-1\n")
    f.write("recipient: residues\n")
    for i in range(len(array)):
        f.write("\t:"+str(i+1)+"\t"+str(array[i])+" \n")
    f.close()
    return

def fragment_map_to_hex(cmap,ticks):
    ### converts a matplotlib colormap into an array of hexcodes for use in Chimera
    colormap = cm.get_cmap(cmap)
    color_range=np.linspace(0,1,ticks)
    hex_map=[]
    for i in range(ticks):
        r,g,b,a = colormap(color_range[i])
        r = int(r*255)
        g = int(g*255)
        b = int(b*255)
        a = int(a*255)
        hex_map.append('#%02x%02x%02x' % (r,g,b))
    return hex_map

def Chimera_attribute_color_string(hex_map,value_array):
    """
    Chimera colorbars are defined from top to bottom, hence the need for a reversed colorstring.
    Chimera is weird, I guess?
    """
    attr_color_array=[]
    colorbar_array=[]
    max_index=len(value_array)-1
    for i in range(len(value_array)):
        attr_color_array.append(str(value_array[i]))
        attr_color_array.append(hex_map[i])
        if i == max_index or i == 0 or value_array[i] == 0:
            colorbar_array.append(str(value_array[max_index-i]))
        else:
            colorbar_array.append("-")
        colorbar_array.append(hex_map[max_index-i])
    attr_color_string = " ".join(x for x in attr_color_array)
    colorbar_string = " ".join(x for x in colorbar_array)
    return attr_color_string,colorbar_string

def Chimera_Overlay_Image(pdbfile,array,image_base,number_of_rotations,make_movie,colormap,hide_atom_mask,keep_files,value_max,value_min,quality):
    ### Adjust parameters based on quality variable, 0 is default for testing,
    ### 1-3 for larger images, 2 and 3 use raytracing
    if quality>3:
        quality=3
    windowsize = ["640 480","800 600","1024 768","2590 1920"]
    supersample = quality+1
    raytrace_true=["","","raytrace true","raytrace true"]
    image_raytrace=["","","raytrace rtwait rtclean","raytrace rtwait rtclean"]


    ### Generate the Chimera-compatible attribute file
    attribute_to_residues(array,f"{image_base}.dat","temp_att","temporary attribute")

    ### Get colormaps and convert to strings for use in Chimera command file.
    hex_mapping = fragment_map_to_hex(colormap,7)
    value_array = np.linspace(value_min,value_max,7)
    attr_color_string,colorbar_string = Chimera_attribute_color_string(hex_mapping,value_array)

    ### Build the Chimera command file
    chi_com_file=open(f"{image_base}.com","w+")
    chi_com_file.write(f"open {pdbfile}\n")                                               #open the pdb file.
    chi_com_file.write(f"windowsize {windowsize[quality]}\n")                               #sets windowsize.
    chi_com_file.write(f"background solid white\n")                                     #background to white.
    chi_com_file.write(f"~nucleotides\n")                                      # turn off nucleotide objects.
    chi_com_file.write(f"~display {hide_atom_mask}\n")                               #hide atoms in the mask.
    chi_com_file.write(f"defattr {image_base}.dat\n")         #define the attribute from the given data file.
    chi_com_file.write(f"rangecolor temp_att {attr_color_string}\n") #apply the color scale to the attribute.
    chi_com_file.write(f"colorkey 0.96,0.05 0.99,0.25 labelSide ")    #puts the colorbar at the bottom right.
    chi_com_file.write(f"left/top labelColor black justification right {colorbar_string}\n")

    ### Take rotational snapshots OR make a rotational movie.
    if make_movie == False: ### Do the rotation snapshots only if the user doesn't want a rotation movie.
        for i in range(number_of_rotations):
            chi_com_file.write(f"copy file {image_base}{i+1}.png png supersample ")
            chi_com_file.write(f"{supersample} {image_raytrace[quality]}\nturn y {360/number_of_rotations}\nwait\n")

    elif make_movie == True: ### Make a movie of the rotation.
        chi_com_file.write(f"movie record {raytrace_true[quality]}\n")
        chi_com_file.write("turn y 1 360\nwait\n")
        chi_com_file.write(f"movie encode framerate 30 output {image_base}.mp4\n")

    chi_com_file.write("stop\n")
    chi_com_file.close()

    ### Run chimera externally using the generated command file.
    os.system(f"chimera --gui {image_base}.com")
    if keep_files == False:
        os.system(f"rm {image_base}.dat {image_base}.com")

def Diff_RMSF(reference,subject):
    ref = np.genfromtxt(reference,skip_header=1,usecols=1)
    sub = np.genfromtxt(subject,skip_header=1,usecols=1)
    data = sub - ref
    return data

def RMSF(reference):
    ref = np.genfromtxt(reference,skip_header=1,usecols=1)
    return ref


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("-p","--pdb",dest="pdb",help="/path/to/.pdb",required=True)
    parser.add_argument("-o","--output",dest="output",help="base output name (no extension)",required=True)
    parser.add_argument("-d","--diff",dest="difference",action="store_true",default=False)
    
    parser.add_argument("-rmsf",dest="rmsf",nargs="+",help="RMSF files to be overlaid.",default=None)
    
    parser.add_argument("-eda",dest="eda_target",nargs="+",help="Residues for desired EDA interactions.",default=None)
    parser.add_argument("-coulomb",dest="cou",nargs="+",help="Coulomb file for EDA",default=None)
    parser.add_Argument("-vdw",dest="vdw",nargs="+",help="Van der Waals file for EDA",default=None)
    
    

    parser.add_argument("-cm","--colormap",dest="colormap",default="viridis",help="Use any matplotlib colormap for your scale.")
    parser.add_argument("-m","--make-movie",dest="makemovie",action="store_true",default=False,help="Renders a rotation video rather than snapshots.")
    parser.add_argument("-r","--rotation",dest="rotations",help="Number of rotations around the vertical to render.",default=1)
    parser.add_argument("-h","--hide",dest="hide_mask",help="AMBER-formatted atom selection mask to explicitly hide side-chains or crystal waters.",default=":1-10000000")
    parser.add_argument("-c","--clean",dest="clean",help="Clean files after running.  <WARNING: No temporary files will be saved.",default=False,action="store_true")
    parser.add_argument("-vmin",dest="vmin",help="Minimum value of colorscale.",default=-1)
    parser.add_argument("-vmax",dest="vmax",help="Maximum value of colorscale.",default=1)
    parser.add_argument("-q","--quality",dest="quality",help="Quality of output image (0,1,2,3).  0 recommended for testing, 2 or 3 for publication quality images.",default=0)
    args=parser.parse_args()

    if args.rmsf != None:
        if args.difference:
            array = Diff_RMSF(args.rsmf[0],args.rmsf[1])
        else:
            array = RMSF(args.rmsf[0])
    elif args.filetype == "EDA":
        if args.eda_target == None:
            print("No EDA targets declared.  Use \"-eda # # #\" to declare residues for EDA interaction totals.")
            exit()
        cou = cou_file_to_EDA_grid(args.file[0])
        vdw = vdw_file_to_EDA_grid(args.file[1])

        full_vdw, full_cou = single_residue_EDA_row(cou,vdw,args.eda_target[0])
        for i in reslist[1:]:
            vdwrow,courow = single_residue_EDA_row(vdw,cou,i)
            full_vdw = full_vdw + vdwrow
            full_cou = full_cou + courow


    elif args.filetype == "correl":



    else:
        print("Unrecognized filetype.")
        exit()

    Chimera_Overlay_Image(args.pdb,args.array,args.output,args.rotations,args.makemovie,args.colormap,args.hide_mask,args.clean,args.vmax,args.vmin,args.quality)
